/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "SlackClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "PlusPlus": cloudflare.D1Database
    "PlusPlusBot": cloudflare.Service
    "PlusPlusInstallations": cloudflare.KVNamespace
    "PlusPlusOAuthStates": cloudflare.KVNamespace
  }
}
